[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["**/*.tmTheme"]
